# Site settings
title: Международная транспортная компания "Оптимал Лоджистик Прайс"
email: info@olp.su
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/olp/" # the subpath of your site, e.g. /blog/
url: "https://oke11o.github.io" # the base hostname & protocol for your site
twitter_username: olp
github_username:  olp

# Build settings
markdown: kramdown
encoding: UTF-8
highlighter: rouge
